# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: who.cr.covid19
canonical: http://fhir.org/guides/who/svc-rc1
name: svc-rc1
status: draft
version: 0.0.1
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2021+
releaseLabel: ci-build
title: WHO Smart Vaccination Certificate
description: TODO
license: CC-BY-SA-4.0
publisher:
  name: WHO
  url: http://who.int
#   email:
# contact:
jurisdiction: http://who.int
# experimental: true
dependencies:
  hl7.fhir.uv.ips: current
